// generated by stringer -type=RepositoryState; DO NOT EDIT

package states

import "fmt"

const _RepositoryState_name = "NewDegradedUnresolvedOperationDetached"

var _RepositoryState_index = [...]uint8{0, 3, 11, 30, 38}

func (i RepositoryState) String() string {
	if i < 0 || i+1 >= RepositoryState(len(_RepositoryState_index)) {
		return fmt.Sprintf("RepositoryState(%d)", i)
	}
	return _RepositoryState_name[_RepositoryState_index[i]:_RepositoryState_index[i+1]]
}
